env:
  global:
    - CC_TEST_REPORTER_ID=6c907649bafd846c81c779acf567dba3f1b212239477c3d08cdd3e18851ac3e4
language: go
go:
  - 1.9

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: ./generate-coverage.sh

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT